In [1]:
import pandas as pd

# CSV file ko DataFrame me load karna
df = pd.read_csv(
    r"C:\Users\Lenovo\Downloads\ecommerce_sales_50000_dirty.csv"
)

# First 5 rows
print(df.head())

C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

   Order_ID  Order_Date Customer_ID   Customer_Name   Age  Gender       City  \
0    100000    8/3/2025       C5426   Customer_5579  41.0    Male    Lucknow
1    100001  11/10/2025       C7396  Customer_13036  42.0    Male     Mumbai
2    100002   6/24/2025       C4005   Customer_4659  20.0    Male  Ahmedabad
3    100003   8/30/2025       C8513   Customer_2613  19.0  Female    Lucknow
4    100004  12/26/2025       C8555   Customer_3074  23.0  Female       Pune

           State  Category Product  Quantity  Unit_Price  Discount_Percent  \
0  Uttar Pradesh   Grocery  Coffee         3       44832                20
1    Maharashtra  Clothing  Tshirt         4        2533                15
2        Gujarat  Clothing   Jeans         4        2847                30
3  Uttar Pradesh    Sports     Bat         2       10727                 0
4    Maharashtra   Grocery     Tea         3       14641                 0

      Sales   Profit Payment_Method
0  107596.8  9576.62    Net Banking
1    8612.2   825.49           Cash
2    7971.6  1307.48           Cash
3   21454.0  6251.87    Net Banking
4   43923.0  5037.75           Card

# Data Inspection (pandas)¶
shape

In [2]:
df.shape

(50500, 16)

# Data Types

In [3]:
df.dtypes

Order_ID              int64
Order_Date              str
Customer_ID             str
Customer_Name           str
Age                 float64
Gender                  str
City                    str
State                   str
Category                str
Product                 str
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Sales               float64
Profit              float64
Payment_Method          str
dtype: object

# Information

In [4]:
df.info

<bound method DataFrame.info of        Order_ID  Order_Date Customer_ID   Customer_Name   Age  Gender  \
0        100000    8/3/2025       C5426   Customer_5579  41.0    Male
1        100001  11/10/2025       C7396  Customer_13036  42.0    Male
2        100002   6/24/2025       C4005   Customer_4659  20.0    Male
3        100003   8/30/2025       C8513   Customer_2613  19.0  Female
4        100004  12/26/2025       C8555   Customer_3074  23.0  Female
...         ...         ...         ...             ...   ...     ...
50495    130471    6/8/2025       C6859   Customer_7637  31.0  Female
50496    106151    4/4/2025       C3153   Customer_5907  26.0    Male
50497    149031   7/22/2025       C3096   Customer_3797  34.0  Female
50498    121146    1/3/2025       C3928   Customer_2992  58.0  Female
50499    109283   1/15/2025       C3551   Customer_4893  43.0  Female

            City          State     Category       Product  Quantity  \
0        Lucknow  Uttar Pradesh      Grocery        Coffee         3
1         Mumbai    Maharashtra     Clothing        Tshirt         4
2      Ahmedabad        Gujarat     Clothing         Jeans         4
3        Lucknow  Uttar Pradesh       Sports           Bat         2
4           Pune    Maharashtra      Grocery           Tea         3
...          ...            ...          ...           ...       ...
50495      Delhi          Delhi       Sports  Cricket Ball         5
50496     Mumbai    Maharashtra       Sports           Bat         3
50497    Lucknow  Uttar Pradesh      Grocery           Tea         1
50498      Delhi          Delhi  Electronics        Laptop         4
50499    Lucknow  Uttar Pradesh       Sports        Helmet         3

       Unit_Price  Discount_Percent      Sales    Profit Payment_Method
0           44832                20  107596.80   9576.62    Net Banking
1            2533                15    8612.20    825.49           Cash
2            2847                30    7971.60   1307.48           Cash
3           10727                 0   21454.00   6251.87    Net Banking
4           14641                 0   43923.00   5037.75           Card
...           ...               ...        ...       ...            ...
50495       42090                20  168360.00  48094.17    Net Banking
50496       33903                30   71196.30   4659.90    Net Banking
50497         867                 5     823.65    209.14           Card
50498        5823                 0   23292.00   3111.02           Cash
50499        1741                25    3917.25    255.27    Net Banking

[50500 rows x 16 columns]>

# First Records

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,Quantity,Unit_Price,Discount_Percent,Sales,Profit,Payment_Method
0,100000,8/3/2025,C5426,Customer_5579,41.0,Male,Lucknow,Uttar Pradesh,Grocery,Coffee,3,44832,20,107596.8,9576.62,Net Banking
1,100001,11/10/2025,C7396,Customer_13036,42.0,Male,Mumbai,Maharashtra,Clothing,Tshirt,4,2533,15,8612.2,825.49,Cash
2,100002,6/24/2025,C4005,Customer_4659,20.0,Male,Ahmedabad,Gujarat,Clothing,Jeans,4,2847,30,7971.6,1307.48,Cash
3,100003,8/30/2025,C8513,Customer_2613,19.0,Female,Lucknow,Uttar Pradesh,Sports,Bat,2,10727,0,21454.0,6251.87,Net Banking
4,100004,12/26/2025,C8555,Customer_3074,23.0,Female,Pune,Maharashtra,Grocery,Tea,3,14641,0,43923.0,5037.75,Card

# Last Records

In [6]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,Quantity,Unit_Price,Discount_Percent,Sales,Profit,Payment_Method
50495,130471,6/8/2025,C6859,Customer_7637,31.0,Female,Delhi,Delhi,Sports,Cricket Ball,5,42090,20,168360.00,48094.17,Net Banking
50496,106151,4/4/2025,C3153,Customer_5907,26.0,Male,Mumbai,Maharashtra,Sports,Bat,3,33903,30,71196.30,4659.90,Net Banking
50497,149031,7/22/2025,C3096,Customer_3797,34.0,Female,Lucknow,Uttar Pradesh,Grocery,Tea,1,867,5,823.65,209.14,Card
50498,121146,1/3/2025,C3928,Customer_2992,58.0,Female,Delhi,Delhi,Electronics,Laptop,4,5823,0,23292.00,3111.02,Cash
50499,109283,1/15/2025,C3551,Customer_4893,43.0,Female,Lucknow,Uttar Pradesh,Sports,Helmet,3,1741,25,3917.25,255.27,Net Banking

# Random Records

In [7]:
df.sample(10)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,Quantity,Unit_Price,Discount_Percent,Sales,Profit,Payment_Method
28241,128241,4/22/2025,C5267,Customer_13613,19.0,Male,NaN,Madhya Pradesh,Electronics,Mobile,4,5556,10,20001.60,3057.37,UPI
28008,128008,12/25/2025,C7864,Customer_8994,57.0,Female,Bhopal,Madhya Pradesh,Furniture,Chair,1,27987,15,23788.95,3123.68,Cash
30364,130364,1/17/2025,C6067,Customer_10553,27.0,Female,Lucknow,Uttar Pradesh,Clothing,Shirt,1,43648,15,37100.80,4472.20,Net Banking
28163,128163,8/6/2025,C7751,Customer_195,29.0,Female,Lucknow,Uttar Pradesh,Electronics,Laptop,2,23497,10,42294.60,11435.50,Cash
30248,130248,2/24/2025,C9989,Customer_9816,26.0,Male,Ahmedabad,Gujarat,Clothing,Shoes,5,22860,25,85725.00,8290.96,Net Banking
11797,111797,6/24/2025,C4412,Customer_13264,28.0,Female,Pune,Maharashtra,Electronics,Mouse,4,13478,0,53912.00,5586.14,Cash
33134,133134,11/5/2025,C1609,Customer_13567,58.0,Female,Delhi,Delhi,Clothing,Shoes,5,35935,25,134756.25,7313.31,Net Banking
111,100111,2/11/2025,C8970,Customer_12419,54.0,Female,Delhi,Delhi,Sports,Bat,1,34108,20,27286.40,NaN,Net Banking
4952,104952,4/11/2025,C7473,Customer_3791,20.0,Female,Ahmedabad,Gujarat,Furniture,Chair,1,49404,25,37053.00,10200.03,UPI
5850,105850,10/18/2025,C3342,Customer_8692,33.0,Female,Pune,Maharashtra,Sports,Cricket Ball,3,47278,15,120558.90,22677.59,Cash

# # Data Quality Cheek

# Missing Value

In [8]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Customer_ID            0
Customer_Name          0
Age                 1009
Gender                 0
City                1009
State                  0
Category               0
Product             1014
Quantity               0
Unit_Price             0
Discount_Percent       0
Sales                  0
Profit              1003
Payment_Method      1007
dtype: int64

# Duplicate Rows¶

In [10]:
df.duplicated().sum()

np.int64(500)

# Unique Values¶

In [11]:
df["Category"].unique()

<ArrowStringArray>
['Grocery', 'Clothing', 'Sports', 'Electronics', 'Furniture']
Length: 5, dtype: str

In [12]:
df["City"].unique()

<ArrowStringArray>
[  'Lucknow',    'Mumbai', 'Ahmedabad',      'Pune',     'Delhi',    'Indore',
    'Jaipur',    'Bhopal',         nan]
Length: 9, dtype: str

In [13]:
df["Payment_Method"].value_counts()

Payment_Method
Cash           12566
Net Banking    12339
Card           12335
UPI            12253
Name: count, dtype: int64

# Missing Percentage Check¶
# Find Percentage

In [14]:
df.isnull().sum() / len(df) * 100

Order_ID            0.000000
Order_Date          0.000000
Customer_ID         0.000000
Customer_Name       0.000000
Age                 1.998020
Gender              0.000000
City                1.998020
State               0.000000
Category            0.000000
Product             2.007921
Quantity            0.000000
Unit_Price          0.000000
Discount_Percent    0.000000
Sales               0.000000
Profit              1.986139
Payment_Method      1.994059
dtype: float64

# Calculation¶

In [16]:
1000 / 50500 * 100

1.9801980198019802

In [17]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [18]:
print(df['Age'].isnull().sum())

0

In [19]:
df['Age'] = df.groupby('Gender')['Age'].transform(
    lambda x: x.fillna(x.median())
)

In [20]:
print(df['Age'].isnull().sum())

0

# AGE — Median

In [21]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [22]:
print(df['Age'].isnull().sum())

0

# CITY — "Unknown"¶

In [24]:
df['City'] = df['City'].fillna('Unknown')

In [25]:
print(df['City'].isnull().sum())

0

# PRODUCT¶

In [26]:
df['Product'] = df['Product'].fillna('Unknown')

# Payment Method¶

In [27]:
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

In [28]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Customer_ID            0
Customer_Name          0
Age                    0
Gender                 0
City                   0
State                  0
Category               0
Product                0
Quantity               0
Unit_Price             0
Discount_Percent       0
Sales                  0
Profit              1003
Payment_Method         0
dtype: int64

# Profit — Median¶

In [29]:
df['Profit'] = df['Profit'].fillna(df['Profit'].median())

In [30]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
State               0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Profit              0
Payment_Method      0
dtype: int64

In [31]:
df.isnull().sum() / len(df) * 100

Order_ID            0.0
Order_Date          0.0
Customer_ID         0.0
Customer_Name       0.0
Age                 0.0
Gender              0.0
City                0.0
State               0.0
Category            0.0
Product             0.0
Quantity            0.0
Unit_Price          0.0
Discount_Percent    0.0
Sales               0.0
Profit              0.0
Payment_Method      0.0
dtype: float64

# Data Cleaning Cheek¶

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50500 non-null  int64
 1   Order_Date        50500 non-null  str
 2   Customer_ID       50500 non-null  str
 3   Customer_Name     50500 non-null  str
 4   Age               50500 non-null  float64
 5   Gender            50500 non-null  str
 6   City              50500 non-null  str
 7   State             50500 non-null  str
 8   Category          50500 non-null  str
 9   Product           50500 non-null  str
 10  Quantity          50500 non-null  int64
 11  Unit_Price        50500 non-null  int64
 12  Discount_Percent  50500 non-null  int64
 13  Sales             50500 non-null  float64
 14  Profit            50500 non-null  float64
 15  Payment_Method    50500 non-null  str
dtypes: float64(3), int64(4), str(9)
memory usage: 9.5 MB

In [35]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'State', 'Category', 'Product', 'Quantity',
       'Unit_Price', 'Discount_Percent', 'Sales', 'Profit', 'Payment_Method'],
      dtype='str')

In [36]:
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Category,Product,Quantity,Unit_Price,Discount_Percent,Sales,Profit,Payment_Method
0,100000,8/3/2025,C5426,Customer_5579,41.0,Male,Lucknow,Uttar Pradesh,Grocery,Coffee,3,44832,20,107596.80,9576.62,Net Banking
1,100001,11/10/2025,C7396,Customer_13036,42.0,Male,Mumbai,Maharashtra,Clothing,Tshirt,4,2533,15,8612.20,825.49,Cash
2,100002,6/24/2025,C4005,Customer_4659,20.0,Male,Ahmedabad,Gujarat,Clothing,Jeans,4,2847,30,7971.60,1307.48,Cash
3,100003,8/30/2025,C8513,Customer_2613,19.0,Female,Lucknow,Uttar Pradesh,Sports,Bat,2,10727,0,21454.00,6251.87,Net Banking
4,100004,12/26/2025,C8555,Customer_3074,23.0,Female,Pune,Maharashtra,Grocery,Tea,3,14641,0,43923.00,5037.75,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50495,130471,6/8/2025,C6859,Customer_7637,31.0,Female,Delhi,Delhi,Sports,Cricket Ball,5,42090,20,168360.00,48094.17,Net Banking
50496,106151,4/4/2025,C3153,Customer_5907,26.0,Male,Mumbai,Maharashtra,Sports,Bat,3,33903,30,71196.30,4659.90,Net Banking
50497,149031,7/22/2025,C3096,Customer_3797,34.0,Female,Lucknow,Uttar Pradesh,Grocery,Tea,1,867,5,823.65,209.14,Card
50498,121146,1/3/2025,C3928,Customer_2992,58.0,Female,Delhi,Delhi,Electronics,Laptop,4,5823,0,23292.00,3111.02,Cash
50499,109283,1/15/2025,C3551,Customer_4893,43.0,Female,Lucknow,Uttar Pradesh,Sports,Helmet,3,1741,25,3917.25,255.27,Net Banking

In [37]:
df.duplicated().sum()

np.int64(500)

In [38]:
duplicates = df[df.duplicated()]

In [39]:
print(duplicates.head())

       Order_ID  Order_Date Customer_ID   Customer_Name   Age  Gender  \
50000    126247  10/31/2025       C3472     Customer_59  27.0    Male
50001    135067   4/28/2025       C7302  Customer_12296  27.0  Female
50002    134590   3/16/2025       C1507   Customer_8537  41.0  Female
50003    116668   2/14/2025       C5085   Customer_8856  33.0  Female
50004    112196   1/13/2025       C1309   Customer_7173  42.0    Male

            City           State     Category   Product  Quantity  Unit_Price  \
50000  Ahmedabad         Gujarat     Clothing    Jacket         2       28656
50001      Delhi           Delhi      Grocery       Tea         4        9110
50002    Lucknow   Uttar Pradesh  Electronics     Mouse         1       37213
50003     Mumbai     Maharashtra      Grocery       Oil         5       26147
50004     Indore  Madhya Pradesh    Furniture  Cupboard         3       48437

       Discount_Percent      Sales    Profit Payment_Method
50000                25   42984.00   6927.29           Cash
50001                25   27330.00   4822.98            UPI
50002                 5   35352.35   3653.44           Cash
50003                15  111124.75  20363.91            UPI
50004                25  108983.25  22052.43    Net Banking

# Duplicate rows remove

In [41]:
df = df.drop_duplicates()

In [42]:
# Confirm¶

In [43]:
print("Rows after removing duplicates:", len(df))
print("Duplicate rows:", df.duplicated().sum())

Rows after removing duplicates: 50000
Duplicate rows: 0

In [44]:
print(df['Order_ID'].duplicated().sum())

0

# verify:¶

In [46]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicates:", df.duplicated().sum())
print("Duplicate Order_ID:", df['Order_ID'].duplicated().sum())

Rows: 50000
Columns: 16
Duplicates: 0
Duplicate Order_ID: 0

# datatype cheek

In [47]:
print(df.dtypes)

Order_ID              int64
Order_Date              str
Customer_ID             str
Customer_Name           str
Age                 float64
Gender                  str
City                    str
State                   str
Category                str
Product                 str
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Sales               float64
Profit              float64
Payment_Method          str
dtype: object

# rder_Date ko datetime

In [49]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [50]:
print(df.dtypes)

Order_ID                     int64
Order_Date          datetime64[us]
Customer_ID                    str
Customer_Name                  str
Age                        float64
Gender                         str
City                           str
State                          str
Category                       str
Product                        str
Quantity                     int64
Unit_Price                   int64
Discount_Percent             int64
Sales                      float64
Profit                     float64
Payment_Method                 str
dtype: object

# data format

In [51]:
print(df['Order_Date'].head())

0   2025-08-03
1   2025-11-10
2   2025-06-24
3   2025-08-30
4   2025-12-26
Name: Order_Date, dtype: datetime64[us]

# New csvFile¶

In [52]:
df.to_csv(
    r"C:\Users\Lenovo\Downloads\ecommerce_sales_50000_cleaned.csv",
    index=False
)

print("New CSV file successfully created!")

New CSV file successfully created!

In [53]:
print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())

(50000, 16)
Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
State               0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Profit              0
Payment_Method      0
dtype: int64
0

In [54]:
print(df.shape)

(50000, 16)

# Null Value Cheek¶

In [55]:
print(df.isnull().sum())

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
State               0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Profit              0
Payment_Method      0
dtype: int64

# Duplicate check

In [56]:
print(df.duplicated().sum())

0

In [57]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [58]:
print(df.dtypes)

Order_ID                     int64
Order_Date          datetime64[us]
Customer_ID                    str
Customer_Name                  str
Age                        float64
Gender                         str
City                           str
State                          str
Category                       str
Product                        str
Quantity                     int64
Unit_Price                   int64
Discount_Percent             int64
Sales                      float64
Profit                     float64
Payment_Method                 str
dtype: object

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50000 non-null  int64
 1   Order_Date        50000 non-null  datetime64[us]
 2   Customer_ID       50000 non-null  str
 3   Customer_Name     50000 non-null  str
 4   Age               50000 non-null  float64
 5   Gender            50000 non-null  str
 6   City              50000 non-null  str
 7   State             50000 non-null  str
 8   Category          50000 non-null  str
 9   Product           50000 non-null  str
 10  Quantity          50000 non-null  int64
 11  Unit_Price        50000 non-null  int64
 12  Discount_Percent  50000 non-null  int64
 13  Sales             50000 non-null  float64
 14  Profit            50000 non-null  float64
 15  Payment_Method    50000 non-null  str
dtypes: datetime64[us](1), float64(3), int64(4), str(8)
memory usage: 9.0 MB